export const SUCCESS = 'SUCCESS';
export const FAILED = 'FAILED';
export const LOADING = 'LOADING';

export const RETRIEVE_USERS = 'RETRIEVE_USERS';
export const GET_USER = 'GET_USER';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';

export const RETRIEVE_ACHIEVEMENTS = 'RETRIEVE_ACHIEVEMENTS';
export const GET_ACHIEVEMENT = 'GET_ACHIEVEMENT';
export const CREATE_ACHIEVEMENT = 'CREATE_ACHIEVEMENT';
export const UPDATE_ACHIEVEMENT = 'UPDATE_ACHIEVEMENT';
export const DELETE_ACHIEVEMENT = 'DELETE_ACHIEVEMENT';

export const RETRIEVE_MATURITY_CATEGORIES = 'RETRIEVE_MATURITY_CATEGORIES';
export const GET_MATURITY_CATEGORY = 'GET_MATURITY_CATEGORY';
export const CREATE_MATURITY_CATEGORY = 'CREATE_MATURITY_CATEGORY';
export const UPDATE_MATURITY_CATEGORY = 'UPDATE_MATURITY_CATEGORY';
export const DELETE_MATURITY_CATEGORY = 'DELETE_MATURITY_CATEGORY';

export const RETRIEVE_MATURITY_LEVELS = 'RETRIEVE_MATURITY_LEVELS';
export const GET_MATURITY_LEVEL = 'GET_MATURITY_LEVEL';
export const CREATE_MATURITY_LEVEL = 'CREATE_MATURITY_LEVEL';
export const UPDATE_MATURITY_LEVEL = 'UPDATE_MATURITY_LEVEL';
export const DELETE_MATURITY_LEVEL = 'DELETE_MATURITY_LEVEL';
