version: '2.4'

services:
  react-client:
    container_name: client
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    ports:
      - 3000:3000
    networks:
        - drive

  react-dev:
    image: node:14-alpine
    container_name: client
    working_dir: /app
    volumes:
      - ../:/app
    stdin_open: true
    ports:
      - 3000:3000
      - 35729:35729
    networks:
        - drive
    command: "npm run dev"

networks:
   drive: 
     name: 'drive'
     driver: bridge