version: '2.4'

services:
  react-client:
    container_name: client
    stdin_open: true
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    volumes:
      - ../:/app
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
        - drive
networks:
   drive: 
     name: 'drive'
     driver: bridge